version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: ils_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ils_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - ils_network

  redis:
    image: redis:7-alpine
    container_name: ils_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - ils_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ils_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ils_network

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data:

networks:
  ils_network:
    driver: bridge